name: R1 Locost
favicon: null
layout_spectrum: 0.01903
typography_spectrum: 0.23529
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9176098643802106
  lightness: 0.5495649673976004
  saturation: 0.37572196451947093
  rhythmicContrast: 0.6329510258510709
purpose: []
